[package]
name = "gadget-ng-vis"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Visualizador de partículas N-body: renderer wgpu + export PNG"

[dependencies]
gadget-ng-core = { path = "../gadget-ng-core" }
wgpu = "30.0.0"
pollster = "1.0.1"
png = "0.18"

[dev-dependencies]
tempfile.workspace = true
